---
name: Kubernetes 1.23 Storage - KVM
version: 1.23.6-6.2.0-1.20220428
publisher: OpenNebula Systems
description: |-
  Beta release.

  Appliance with preinstalled Kubernetes 1.23 to work as a multi-master/multi-node cluster orchestrated by [OneFlow](https://docs.opennebula.io/6.2/management_and_operations/multivm_service_management/appflow_elasticity.html).

  Preconfigured with Canal CNI networking (Calico and Flannel) and CNCF Longhorn to handle persistence.

  Please refer to the [documentation](https://docs.opennebula.io/appliances/service/kubernetes_service.html).
short_description: Appliance with preinstalled Kubernetes 1.23 for KVM hosts (Storage workers)
tags:
- kubernetes
- service
- ubuntu
type: VMTEMPLATE
format: qcow2
creation_time: 1651140000
os-id: Ubuntu
os-release: "20.04.4 LTS"
os-arch: x86_64
hypervisor: KVM
opennebula_version: >-
  6.2, 6.3, 6.4
opennebula_template:
  sched_requirements: HYPERVISOR=kvm
  context:
    grow_fs: "/ /var/lib/longhorn"
    network: "YES"
    report_ready: "YES"
    token: "YES"
    oneapp_vrouter_eth1_vip0: "$ONEAPP_VROUTER_ETH1_VIP0"
    oneapp_vnf_lb0_ip: "$ONEAPP_VNF_LB0_IP"
    oneapp_k8s_port: "$ONEAPP_K8S_PORT"
    oneapp_k8s_pods_network: "$ONEAPP_K8S_PODS_NETWORK"
    oneapp_storage_device: "$ONEAPP_STORAGE_DEVICE"
    oneapp_storage_label: "STORAGE"
    oneapp_storage_filesystem: "$ONEAPP_STORAGE_FILESYSTEM"
    oneapp_storage_mountpoint: "/var/lib/longhorn"
    ssh_public_key: "$USER[SSH_PUBLIC_KEY]"
  cpu: "2"
  vcpu: "2"
  graphics:
    listen: "0.0.0.0"
    type: vnc
  inputs_order: ""
  memory: "3072"
  os:
    arch: x86_64
  user_inputs: {}
logo: kubernetes.png
disks:
- "Kubernetes 1.23 OS disk - KVM"
- "Kubernetes 1.23 Storage disk - KVM"
